name: 'general_lib_flutter'
description: 'Library for make flutter more easy and more short with universal extension, utils, and more.'
version: '0.0.23'
environment: 
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.10.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  universal_io: '^2.2.2'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.1'
  general_lib: '^0.0.43'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
repository: 'https://github.com/azkadev/general_lib_flutter'
