name: 'general_lib_flutter'
description: 'Library for make flutter more easy and more short with universal extension, utils, and more.'
version: '0.0.41'
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  general_lib: '^0.0.62'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
repository: 'https://github.com/azkadev/general_lib_flutter'
homepage: 'https://youtube.com/@azkadev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
